export const STORE_PRODUCTS_REQUEST = "PRODUCT.STORE_PRODUCTS_REQUEST";
export const STORE_PRODUCTS_SUCCESS = "PRODUCT.STORE_PRODUCTS_SUCCESS";
export const STORE_PRODUCTS_FAILURE = "PRODUCT.STORE_PRODUCTS_FAILURE";
