export const STORE_PRODUCTS_REQUEST = "PRODUCT.STORE_PRODUCTS_REQUEST";
export const STORE_PRODUCTS_SUCCESS = "PRODUCT.STORE_PRODUCTS_SUCCESS";
export const STORE_PRODUCTS_FAILURE = "PRODUCT.STORE_PRODUCTS_FAILURE";

export const SAVE_ITEM_DATA_BASE_REQUEST =
  "PRODUCT.SAVE_ITEM_DATA_BASE_REQUEST";
export const SAVE_ITEM_DATA_BASE_SUCCESS =
  "PRODUCT.SAVE_ITEM_DATA_BASE_SUCCESS";
export const SAVE_ITEM_DATA_BASE_FAILURE =
  "PRODUCT.SAVE_ITEM_DATA_BASE_FAILURE";
